config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :notices
    get "/notices/:id/send_notice" => "notices#send_notice"
    get "dashboard", to: "database_usage#dashboard", as: :dashboard
    get "daily_usage/:date", to: "database_usage#daily_usage", as: :daily_usage
  end

  # Adding these routes connects those requests to the appropriate actions of the errors controller.
  # Using match ... :via => :all allows the error pages to be displayed for any type of request (GET, POST, PUT, etc.)
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords:     'users/passwords'}

  devise_scope :user do
    get 'users/password', :to => 'users/registrations#password'
  end

  root "pages#home"

  get 'file_records/active_url'
  get 'summary/aact'

  get "/airbrake"             => "pages#airbrake"

  get "/data_dictionary"      => "dictionary#show"
  get "/activities"           => "database_activity#show"
  get 'dictionary/show'
  # get "admin/notices/:id/send_notice" => "admin/notices#send_notice"
  get "/connect"              => "pages#connect"
  # TODO: remove legacy routes and its references
  # get "/download"             => "pages#download"
  # get "/covid_19"             => "pages#covid_19"
  # get "/snapshots"            => "pages#snapshots"
  # get "/pipe_files"           => "pages#pipe_files"
  get 'faq'                   => "pages#faq"
  get "/learn_more"           => "pages#learn_more"
  get "/covid_19_fields"      => "pages#covid_19_fields"
  get "/pipe_files_with_r"    => "pages#pipe_files_with_r"
  get "/pipe_files_with_sas"  => "pages#pipe_files_with_sas"
  get "/pgadmin"              => "pages#pgadmin"
  get "/points_to_consider"   => "pages#points_to_consider"
  get "/postgres"             => "pages#postgres"
  get "/r"                    => "pages#r"
  get "/sanity_check_report"  => "pages#sanity_check", as: :sanity_check
  get "/sas"                  => "pages#sas"
  get "/saved_query_doc"      => "pages#saved_query_doc"
  get "/schema"               => "pages#schema"
  get "/snapshot_archive"     => "pages#snapshot_archive"
  get "/technical_documentation"    => "pages#technical_documentation"
  get "/update_policy"        => "pages#update_policy"
  get "/deploy_code"          => "pages#deploy_code"
  get "/contactus"            => "pages#contactus"

  get '/history', to: 'background_jobs#history'
  get '/admin/history', to: 'background_jobs#admin_history'
  get '/queries', to: 'saved_queries#index'
  get '/my/queries', to: 'saved_queries#my_queries'
  get "/playground"           => "playground#index", as: :playground
  get "/playground/:id"       => "playground#show_results", as: :show_results
  get "job_status/:id"        => "playground#job_status", as: :job_status
  get "/install_postgres"     => "postgres_documentation#install_postgres"
  get "/credentials"          => "credentials#show"

  get "/admin_run_loads"      => "faq#admin_run_loads"
  get "/admin_remove_user"    => "faq#admin_remove_user"
  get "/admin_add_project"    => "faq#admin_add_project"
  get "/faq_proj_gather_info" => "faq#proj_gather_info"
  get "/faq_proj_change_app"  => "faq#proj_change_app"

  get "/support_grant_permission"  => "faq#support_grant_permission"
  get "/support_registration_failed"  => "faq#support_registration_failed"
  get "/support_user_cannot_access_db"  => "faq#support_user_cannot_access_db"

  get "/tech_access_servers"  => "faq#tech_access_servers"
  get "/tech_apply_ctgov_changes"  => "faq#tech_apply_ctgov_changes"
  get "/tech_deploy_code"     => "faq#tech_deploy_code"

  #beta
  get "/beta/migration" => "beta#migration"
  get "/beta/schema"     => "beta#schema"
  get "/beta/data_dictionary" => "beta#data_dictionary"

  #archive
  get "/archive"           => "archive#archive"
  get "/archive/data_dictionary" => "archive#data_dictionary"
  get "/archive/schema"    => "archive#schema"
  get "/archive/download"  => "archive#download"
  get "/archive/snapshots" => "archive#snapshots"
  get "/archive/pipe_files" => "archive#pipe_files"
  get "/archive/covid_19"   => "archive#covid_19"
  get "/archive/pipe_files_with_r"    => "archive#pipe_files_with_r"
  get "/archive/pipe_files_with_sas"  => "archive#pipe_files_with_sas"

  #digitalocean
  get "/static/:type/:time/:filename(:format)" => "file_records#active_url"

  resources :documentation, only: [:index, :show, :edit, :update] do
    collection do
      get :download_csv
    end
  end

  # TODO: review and optimize naming before releasing
  resources :downloads, only: [:index] do
    collection do
      get 'snapshots'
      get 'postgres_instructions'
      get 'flatfiles_instructions'
      get 'covid19_instructions'
    end
  end


  resources :file_records, only: [:index, :show]
  resources :definitions, only: [:index]
  resources :data_definitions
  resources :users
  resources :shared_data, param: :schema_name
  resources :release_notes
  resources :releases
  resources :datasets
  resources :attachments
  resources :use_cases
  resources :use_case_attachments
  resources :events
  resources :verifiers
  resources :saved_queries
  resources :study_statistics_comparisons
  resources :background_jobs, path: '/history', only: [:index, :show, :destroy]
  resources :study_searches

end

app/controllers/downloads_controller.rb
class DownloadsController < ApplicationController
  before_action :set_snapshots_service

  def index
    @latest_snapshots = @snapshots_service.fetch_latest_snapshots
  end

  def snapshots
    puts "Fetching daily and monthly snapshots with:", params
    @type = params[:type]
    @all_snapshots = @snapshots_service.fetch_all_snapshots_by_type(@type)
    @year = params[:year] || Date.today.year.to_s
    @paginated_daily_snapshots = Kaminari.paginate_array(@all_snapshots[:daily] || []).page(params[:page]).per(10)
  end

  def postgres_instructions
    render 'downloads/instructions/postgres'
  end

  def flatfiles_instructions
    render 'downloads/instructions/flatfiles'
  end

  def covid19_instructions
    render 'downloads/instructions/covid19'
  end

  private

  def set_snapshots_service
    @snapshots_service = SnapshotsService.new
  end
end

app/helpers/downloads_helper.rb
module DownloadsHelper
  include ActionView::Helpers::TagHelper

  # TODO: remove description_title
  SNAPSHOT_CONFIG = {
    'pgdump' => {
      title: 'PostgreSQL Database Dump', # PostgreSQL Database Dump
      description_title: 'About PostgreSQL Database Dump',
      view_all_text: 'Database Dumps',
      instructions_path: 'downloads/postgres_instructions',
      description_content: lambda do |helper|
        helper.safe_join([
          helper.content_tag(:p, 'Use this file to create a complete copy of the AACT database on your own PostgreSQL server.'),
          helper.content_tag(:div, helper.content_tag(:code, 'pg_restore -c -d your_database_name path_to_downloaded_file'), class: 'code-snippet'),
        ], "")
      end
    },
    'flatfiles' => {
      title: 'Flat Text Files',
      description_title: 'About Flat Files',
      view_all_text: 'Flat Files',
      instructions_path: 'downloads/flatfiles_instructions',
      description_content: lambda do |helper|
        helper.safe_join([
          helper.content_tag(:p, 'Use these pipe-delimited text files to import AACT data into any database or analysis tool. Each file corresponds to a table in the AACT database schema.'),
        ])

      end
    },
    'covid' => {
      title: 'COVID-19 Spreadsheets',
      description_title: 'About COVID-19 Spreadsheets',
      view_all_text: 'COVID-19 Spreadsheets',
      instructions_path: 'downloads/covid19_instructions',
      description_content: lambda do |helper|
        helper.safe_join([
          helper.content_tag(:p, 'These files contain current clinical studies related to COVID-19 from ClinicalTrials.gov as of the date of file creation. Each file allows users without advanced database skills to explore the trials in a spreadsheet format.'),
          helper.content_tag(:p) do
            helper.content_tag(:strong, 'Please Note: ') +
            'COVID-19 spreadsheets are no longer actively generated. Please check the "Last Exported" date above for the most recent available data.'
          end
        ])
      end
    }
  }

  def snapshot_title(type)
    SNAPSHOT_CONFIG.dig(type, :title) || "Unknown Snapshot Type"
  end

  def snapshot_description_title(type)
    SNAPSHOT_CONFIG.dig(type, :description_title) || "About This File"
  end

  def snapshot_view_all_text(type)
    SNAPSHOT_CONFIG.dig(type, :view_all_text) || "Snapshots"
  end

  def snapshot_description_content(type)
    content = SNAPSHOT_CONFIG.dig(type, :description_content)
    if content.is_a?(Proc)
      content.call(self)
    else
      content_tag(:p, "No description available yet.")
    end
  end

  def snapshot_instructions_path(type)
    SNAPSHOT_CONFIG.dig(type, :instructions_path)
  end
end

app/views/downloads/_empty_state.html.erb
<div class="empty-state">
  <h3 class="empty-state-title"><%= title %></h3>
  <div class="empty-state-message">
    <%= message %>
  </div>
</div>

app/views/downloads/_snapshot_card.html.erb
<%# dynamic class name based on snapshot type %>
<div class="snapshot-card <%= snapshot["type"] %>">
  <div class="snapshot-header">
    <div class="snapshot-type <%= snapshot["type"] %>"><%= snapshot_title(snapshot["type"]) %></div>
    <div class="snapshot-date">Last Exported: <%= snapshot["date"] %></div>
  </div>
  <div class="snapshot-content">
    <div class="snapshot-description">
      <%= snapshot_description_content(snapshot["type"]) %>
    </div>
    <div class="snapshot-details">
      <div class="detail-item">
        <span class="detail-label">File:</span>
        <span class="detail-value"><%= snapshot["file_name"] %></span>
      </div>
      <div class="detail-item">
        <span class="detail-label">Size:</span>
        <span class="detail-value"><%= snapshot["size"] %></span>
      </div>
    </div>

    <div class="snapshot-actions">
      <%= link_to snapshot_instructions_path(snapshot["type"]), class: "snapshots-action-button secondary" do %>
        Instructions
      <% end %>
      <%= link_to snapshots_downloads_path(type: snapshot["type"]), class: "snapshots-action-button secondary" do %>
        Historical Data
      <% end %>
      <%= link_to snapshot["download_url"], class: "snapshots-action-button primary", download: snapshot["file_name"] do %>
        Download File
      <% end %>
    </div>
  </div>
</div>

app/views/downloads/index.html.erb
<div class="snapshots-wrapper">
  <h1 class="snapshots-title">Latest AACT Database Snapshots</h1>
  <% if @latest_snapshots.present? %>
    <div class="snapshots-list">
      <% @latest_snapshots.each do |snapshot| %>
        <%= render partial: 'snapshot_card', locals: { snapshot: snapshot } %>
      <% end %>
    </div>
  <% else %>
    <%= render partial: 'empty_state', locals: {
      title: "No Snapshots Available",
      message: "We couldn't retrieve the latest database snapshots at this moment. This might be due to scheduled maintenance or a temporary connection issue. Please try again later."
    } %>
  <% end %>
    <div class="additional-resources">
      <div class="resource-header">
        <h4>Additional Resources</h4>
      </div>
      <div class="resource-links">
        <a href="/learn_more" class="resource-link">Learn More About AACT Data</a>
        <a href="/documentation" class="resource-link">View Documentation</a>
      </div>
    </div>
  <% if Rails.env.development? && @latest_snapshots.nil? %>
    <div class="debug-info">
      <strong>Debug:</strong> Latest snapshots data is nil.
    </div>
  <% elsif Rails.env.development? %>
    <div class="debug-info">
      <strong>Debug:</strong> Latest snapshots data type: <%= @latest_snapshots.class.name %>
      <pre><%= JSON.pretty_generate(@latest_snapshots) rescue @latest_snapshots.inspect %></pre>
    </div>
  <% end %>
</div>

app/views/downloads/snapshots.html.erb
<div class="snapshots-wrapper">
  <div class="details-controls">
    <%= link_to "Back", downloads_path, class: "btn btn-secondary control-btn" %>
    <div class="snapshots-title"><%= snapshot_title(@type) %></div>
  </div>

  <% if @all_snapshots[:daily].any? || @all_snapshots[:monthly].keys.any? %>
    <!-- Daily Snapshots Section -->
    <div class="snapshots-section">
      <h2 class="snapshots-section-title">Recent Daily Snapshots</h2>
      <% if @paginated_daily_snapshots.any? %>
        <div class="snapshots-grid-table">
          <!-- Grid Header -->
          <div class="snapshots-grid-row snapshots-grid-header">
            <div>Date</div>
            <div>File Name</div>
            <div>Size</div>
            <div>Actions</div>
          </div>
        <!-- Grid Rows -->
          <% @paginated_daily_snapshots.each do |snapshot| %>
            <div class="snapshots-grid-row">
              <div data-label="Date:"><strong><%= snapshot["date"] %></strong></div>
              <div data-label="File:"><%= snapshot["file_name"] %></div>
              <div data-label="Size:"><%= snapshot["size"] %></div>
              <div class="snapshots-grid-actions">
                <%= link_to snapshot["download_url"], class: "snapshots-action-button primary", download: snapshot["file_name"] do %>
                  Download
                <% end %>
              </div>
            </div>
          <% end %>
        <% else %>
          <%= render partial: 'empty_state', locals: {
            title: "No Daily Snapshots",
            message: "No daily snapshots are currently available for #{snapshot_title(@type)}. Daily snapshots are typically created each night."
          } %>
        <% end %>
      </div>

      <!-- Pagination for Daily Snapshots -->
      <% if @paginated_daily_snapshots.any? %>
        <div class="pagination-wrapper mt-3">
          <%= paginate @paginated_daily_snapshots,
            class: "pagination",
            inner_window: 2,
            outer_window: 0
          %>
        </div>
      <% end %>
    </div>

    <!-- Monthly Snapshots Section -->
    <div class="snapshots-section mt-5">
      <h2 class="snapshots-section-title">Monthly Archives</h2>
      <!-- TODO: Refactor out sorting logic from the view layer-->
      <!-- Year Navigation -->
      <div class="year-navigation">
        <% if @all_snapshots[:monthly].keys.any? %>
          <% @all_snapshots[:monthly].keys.sort.reverse.each do |year| %>
            <%= link_to year,
                snapshots_downloads_path(type: @type, year: year),
                class: "year-link #{year == @year ? 'selected-year' : ''}" %>
          <% end %>
        <% end %>
      </div>

      <% if @all_snapshots[:monthly][@year].present? && @all_snapshots[:monthly][@year].any? %>
        <div class="snapshots-grid-table">
          <div class="snapshots-grid-row snapshots-grid-header">
            <div>Date</div>
            <div>File Name</div>
            <div>Size</div>
            <div>Actions</div>
          </div>

          <% @all_snapshots[:monthly][@year].sort_by { |s| s["date"] }.reverse.each do |snapshot| %>
            <div class="snapshots-grid-row">
              <div data-label="Date:"><%= snapshot["date"] %></div>
              <div data-label="File:"><%= snapshot["file_name"] %></div>
              <div data-label="Size:"><%= snapshot["size"] %></div>
              <div class="snapshots-grid-actions">
                <%= link_to snapshot["download_url"], class: "snapshots-action-button primary", download: snapshot["file_name"] do %>
                  Download
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% else %>
        <%= render partial: 'empty_state', locals: {
          title: "No Monthly Archives",
          message: "No monthly archives are currently available for #{@year}. Monthly snapshots are created at the beginning of each month."
        } %>
      <% end %>
    </div>
  <% else %>
    <!-- Neither Daily or Monthly Snapshots available -->
    <%= render partial: 'empty_state', locals: {
      title: "No Snapshots Available",
      message: "We couldn't retrieve any #{snapshot_title(@type)} snapshots at this moment. This might be due to scheduled maintenance or a temporary connection issue. Please try again later."
    } %>
  <% end %>

  <% if Rails.env.development? %>
    <div class="debug-info mt-4">
      <strong>Debug:</strong> Snapshot type: <%= @type %>
      <pre><%= JSON.pretty_generate(@all_snapshots) rescue @all_snapshots.inspect %></pre>
    </div>
  <% end %>
</div>