config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :notices
    get "/notices/:id/send_notice" => "notices#send_notice"
    get "dashboard", to: "database_usage#dashboard", as: :dashboard
    get "daily_usage/:date", to: "database_usage#daily_usage", as: :daily_usage
  end

  # Adding these routes connects those requests to the appropriate actions of the errors controller.
  # Using match ... :via => :all allows the error pages to be displayed for any type of request (GET, POST, PUT, etc.)
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords:     'users/passwords'}

  devise_scope :user do
    get 'users/password', :to => 'users/registrations#password'
  end

  root "pages#home"

  get 'file_records/active_url'
  get 'summary/aact'

  get "/airbrake"             => "pages#airbrake"

  get "/data_dictionary"      => "dictionary#show"
  get "/activities"           => "database_activity#show"
  get 'dictionary/show'
  # get "admin/notices/:id/send_notice" => "admin/notices#send_notice"
  get "/connect"              => "pages#connect"
  # TODO: remove legacy routes and its references
  # get "/download"             => "pages#download"
  # get "/covid_19"             => "pages#covid_19"
  # get "/snapshots"            => "pages#snapshots"
  # get "/pipe_files"           => "pages#pipe_files"
  get 'faq'                   => "pages#faq"
  get "/learn_more"           => "pages#learn_more"
  get "/covid_19_fields"      => "pages#covid_19_fields"
  get "/pipe_files_with_r"    => "pages#pipe_files_with_r"
  get "/pipe_files_with_sas"  => "pages#pipe_files_with_sas"
  get "/pgadmin"              => "pages#pgadmin"
  get "/points_to_consider"   => "pages#points_to_consider"
  get "/postgres"             => "pages#postgres"
  get "/r"                    => "pages#r"
  get "/sanity_check_report"  => "pages#sanity_check", as: :sanity_check
  get "/sas"                  => "pages#sas"
  get "/saved_query_doc"      => "pages#saved_query_doc"
  get "/schema"               => "pages#schema"
  get "/snapshot_archive"     => "pages#snapshot_archive"
  get "/technical_documentation"    => "pages#technical_documentation"
  get "/update_policy"        => "pages#update_policy"
  get "/deploy_code"          => "pages#deploy_code"
  get "/contactus"            => "pages#contactus"

  get '/history', to: 'background_jobs#history'
  get '/admin/history', to: 'background_jobs#admin_history'
  get '/queries', to: 'saved_queries#index'
  get '/my/queries', to: 'saved_queries#my_queries'
  get "/playground"           => "playground#index", as: :playground
  get "/playground/:id"       => "playground#show_results", as: :show_results
  get "job_status/:id"        => "playground#job_status", as: :job_status
  get "/install_postgres"     => "postgres_documentation#install_postgres"
  get "/credentials"          => "credentials#show"

  get "/admin_run_loads"      => "faq#admin_run_loads"
  get "/admin_remove_user"    => "faq#admin_remove_user"
  get "/admin_add_project"    => "faq#admin_add_project"
  get "/faq_proj_gather_info" => "faq#proj_gather_info"
  get "/faq_proj_change_app"  => "faq#proj_change_app"

  get "/support_grant_permission"  => "faq#support_grant_permission"
  get "/support_registration_failed"  => "faq#support_registration_failed"
  get "/support_user_cannot_access_db"  => "faq#support_user_cannot_access_db"

  get "/tech_access_servers"  => "faq#tech_access_servers"
  get "/tech_apply_ctgov_changes"  => "faq#tech_apply_ctgov_changes"
  get "/tech_deploy_code"     => "faq#tech_deploy_code"

  #beta
  get "/beta/migration" => "beta#migration"
  get "/beta/schema"     => "beta#schema"
  get "/beta/data_dictionary" => "beta#data_dictionary"

  #archive
  get "/archive"           => "archive#archive"
  get "/archive/data_dictionary" => "archive#data_dictionary"
  get "/archive/schema"    => "archive#schema"
  get "/archive/download"  => "archive#download"
  get "/archive/snapshots" => "archive#snapshots"
  get "/archive/pipe_files" => "archive#pipe_files"
  get "/archive/covid_19"   => "archive#covid_19"
  get "/archive/pipe_files_with_r"    => "archive#pipe_files_with_r"
  get "/archive/pipe_files_with_sas"  => "archive#pipe_files_with_sas"

  #digitalocean
  get "/static/:type/:time/:filename(:format)" => "file_records#active_url"

  resources :documentation, only: [:index, :show, :edit, :update] do
    collection do
      get :download_csv
    end
  end

  # TODO: review and optimize naming before releasing
  resources :downloads, only: [:index] do
    collection do
      get 'snapshots'
      get 'postgres_instructions'
      get 'flatfiles_instructions'
      get 'covid19_instructions'
    end
  end


  resources :file_records, only: [:index, :show]
  resources :definitions, only: [:index]
  resources :data_definitions
  resources :users
  resources :shared_data, param: :schema_name
  resources :release_notes
  resources :releases
  resources :datasets
  resources :attachments
  resources :use_cases
  resources :use_case_attachments
  resources :events
  resources :verifiers
  resources :saved_queries
  resources :study_statistics_comparisons
  resources :background_jobs, path: '/history', only: [:index, :show, :destroy]
  resources :study_searches

end

app/models/data_definition.rb
require 'active_support/all'
class DataDefinition < ActiveRecord::Base
  validates :db_section, :table_name, :column_name, :data_type, :source, presence: true

  def self.default_data_definitions
    Roo::Spreadsheet.open("#{Rails.public_path}/documentation/aact_data_definitions.xlsx")
  end

  def self.populate(data=self.default_data_definitions)
    self.destroy_all
    self.populate_from_file(data)
    self.populate_row_counts
    Enumeration.populate
  end

  def self.populate_from_file(data=self.default_data_definitions)
    header = data.first
    dataOut = []
    (2..data.last_row).each do |i|
      row = Hash[[header, data.row(i)].transpose]
      if !row['table'].nil? and !row['column'].nil?
        new(:db_section   => row['db section'].try(:downcase),
            :db_schema    => row['db schema'].try(:downcase),
            :table_name   => row['table'].try(:downcase),
            :column_name  => row['column'].try(:downcase),
            :data_type    => row['data type'].try(:downcase),
            :source       => row['source'].try(:downcase),
            :ctti_note    => row['CTTI note'],
            :nlm_link     => row['nlm doc'],
           ).save!
      end
    end
  end

  def self.populate_row_counts
    # save count for each table where the primary key is id
    rows=where("column_name='id'")
    populate_from_file if rows.size==0
    rows.each{|row|
      begin
        results=Public::PublicBase.connection.execute("select count(*) from #{row.table_name}")
        row.row_count=results.getvalue(0,0) if results.ntuples == 1
        row.save
      rescue
        puts ">>>>  could not get row count for #{row.table_name}"
      end
    }
    # Study table is only one where primary key is NCT_ID, not ID. Determine/save row count separately
    study_row=where("lower(table_name) = 'studies' and lower(column_name)='nct_id'").first
    study_row.row_count=Public::Study.count
    study_row.save!
  end

  def self.single_study_tables
    [
      'brief_summaries',
      'designs',
      'detailed_descriptions',
      'eligibilities',
      'participant_flows',
      'calculated_values',
      'studies'
    ]
  end

  def self.make_json_file(schema='ctgov')
    if schema == "archive"
      file_name="aact_archive_data_definitions"
    elsif schema == "beta"
      file_name="aact_beta_data_definitions"
    else
      file_name="aact_data_definitions"
    end
    data = Roo::Spreadsheet.open("#{Rails.configuration.aact[:static_files_directory]}/documentation/#{file_name}.xlsx")

    unless File.exists?("public/#{file_name}.json")
      header = data.first
      dataOut = []
      (2..data.last_row).each do |i|
        row = Hash[[header, data.row(i)].transpose]
        if !row['table'].nil? and !row['column'].nil?
            dataOut << fix_attribs(row)
        end
      end
      File.open("public/#{file_name}.json","w") do |f|
        f.write(dataOut.to_json)
      end
    end

    return JSON.parse(File.read("public/#{file_name}.json"))

  end

  def self.fix_attribs(hash)
    results_url=Util::FilePresentationManager.new.nlm_results_data_url
    protocol_url=Util::FilePresentationManager.new.nlm_protocol_data_url

    enums=Enumeration.new.enums
    enum_tabs=enums.map {|row| row[0]}
    enum_cols=enums.map {|row| row[1]}
    tab=Rails::Html::FullSanitizer.new.sanitize(hash["table"]).downcase
    col=hash['column'].downcase

    if hash['source']
      fixed_content=hash['source'].gsub(/\u003c/, "&lt;").gsub(/>/, "&gt;")
      hash['source']=fixed_content
    end

    if enum_tabs.include? tab and enum_cols.include? col
      dd=DataDefinition.where('table_name=? and column_name=?',tab,col).first
      if dd and !dd.enumerations.nil?
        str="<select>"
        dd.enumerations.first(3).each{|e|
          cnt=e.last.first
          pct=e.last.last
          str=str+"<option>"+cnt+" ("+pct+")&nbsp&nbsp; - "+e.first+"</option>"
        }
        str=str+'</select>'
        hash['enumerations']=str.html_safe
      end
    end

    if hash['nlm doc'].present?
      url=hash["db section"].downcase == "results" ? results_url : protocol_url
      hash['nlm doc'] = "<a href=#{url}##{hash['nlm doc']} class='navItem' target='_blank'><i class='fa fa-book'></i></a>".html_safe
    end

    if (col == 'id') or (tab.downcase == 'studies' and col == 'nct_id')
      # If this is the table's primary key, display row count.
      results=ActiveRecord::Base.connection.execute("SELECT row_count FROM data_definitions WHERE table_name='#{tab}' and column_name='#{col}'")
      if results.ntuples > 0
        row_count=results.getvalue(0,0).to_s.reverse.gsub(/(\d{3})(?=\d)/, '\\1,').reverse
        hash['row count']=row_count
      else
        hash['row count']=0
      end
      hash['table'] = "<span class='primary-key' id='#{tab}'>#{hash['table']}</span>"
    end

    return hash
  end


end

app/controllers/data_definitions_controller.rb
class DataDefinitionsController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found
  before_action :set_data_definition, only: [:edit, :update, :show, :destroy]
  before_action :is_admin?
  
  def index
    @data_definitions = DataDefinition.all
  end

  def new
    @data_definition = DataDefinition.new
  end

  def edit
  end

  def show
  end
 
  def create
    @data_definition = DataDefinition.new(data_definition_params)
    if @data_definition.save
      flash.notice = "The Data Definition record was created successfully."
      redirect_to data_definitions_path
    else
      flash.now.alert = @data_definition.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    if @data_definition.update(data_definition_params)
      flash.notice = "The Data Definition record was updated successfully."
      redirect_to data_definitions_path
    else
      flash.now.alert = @data_definition.errors.full_messages.to_sentence
      render :edit
    end
  end

  def destroy
    @data_definition.destroy
    redirect_to data_definitions_path, notice: 'The Data Definition record was successfully deleted.'
  end
  
  private
    def set_data_definition
      @data_definition = DataDefinition.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def data_definition_params
      params.require(:data_definition)
        .permit(:db_section, :table_name, :column_name, :data_type, :source, :ctti_note, :nlm_link)
    end

    def catch_not_found(e)
      Rails.logger.debug("We had a not found exception.")
      flash.alert = e.to_s
      redirect_to data_definitions_path
    end
end

app/views/data_definitions/_form.html.erb
<%= form_for(data_definition) do |f| %>
  <% if data_definition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(data_definition.errors.count, "error") %> prohibited this Data Definitions from being saved:</h2>
      <ul>
        <% data_definition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-body">
    <div class="container-fluid">
      <%= f.label :db_section %>
      <%= f.text_field :db_section, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :table_name %>
      <%= f.text_field :table_name, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :column_name %>
      <%= f.text_field :column_name, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :data_type %>
      <%= f.text_field :data_type, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :source %>
      <%= f.text_area :source, rows: 2, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :ctti_note %>
      <%= f.text_area :ctti_note, rows: 4, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :nlm_link %>
      <%= f.text_field :nlm_link, class: "form-control" %>
      <% if data_definition.nlm_link.present? %>
        <% results_url = Util::FilePresentationManager.new.nlm_results_data_url %>
        <% protocol_url = Util::FilePresentationManager.new.nlm_protocol_data_url %>
        <% url = data_definition.db_section.downcase == "results" ? results_url : protocol_url %>
        <%= link_to "Preview", "#{url}##{data_definition.nlm_link}", class: 'preview-link', target: '_blank' %>
      <% end %>
    </div>
    <div class="pb-3">
    </div>
    <div class="actions container-fluid">
      <%= f.submit :class => "old-btn"%>
    </div>
    <div class="pb-4">
    </div>
  </div>
<% end %>

app/views/data_definitions/edit.html.erb
<div class="modal-body">
  <h1>Edit Data Definition</h1>
  <%= render 'form', data_definition: @data_definition %>
  <%= link_to 'Back', data_definition_path, :class => "btn btn-primary btn-sm" %>
</div>

app/views/data_definitions/index.html.erb
<div class="container">
  <div class="pb-5">
    <h1>Data Definitions</h1>
    <%= link_to 'New Data Definition', new_data_definition_path, :class => "btn btn-primary btn-sm" %>
  </div>

  <div class="">
    <table class="table table-sm table-striped">
      <thead>
        <tr>
          <th style="text-align: center">table_name.column_name</th>
          <th style="text-align: center">db_section</th>
          <th style="text-align: center">data_type</th>
          <th style="text-align: center">source</th>
          <th style="text-align: center">ctti_note</th>
          <th style="text-align: center">nlm_link</th>
          <th colspan="6"></th>
        </tr>
      </thead>
      <tbody>
        <% @data_definitions.each do |data_definition| %>
          <tr>
            <td style="text-align: center"><%= link_to "#{data_definition.table_name}.#{data_definition.column_name}", data_definition_path(data_definition) %></td>
            <td style="text-align: center"><%= data_definition.db_section %></td>
            <td style="text-align: center"><%= data_definition.data_type %></td>
            <td style="text-align: center"><%= data_definition.source %></td>
            <td style="text-align: center"><%= data_definition.ctti_note %></td>
            <td style="text-align: center">
              <% if data_definition.nlm_link.present? %>
                <% results_url = Util::FilePresentationManager.new.nlm_results_data_url %>
                <% protocol_url = Util::FilePresentationManager.new.nlm_protocol_data_url %>
                <% url = data_definition.db_section.downcase == "results" ? results_url : protocol_url %>
                <%= link_to raw("<i class='fa fa-book'></i>"), "#{url}##{data_definition.nlm_link}", class: 'navItem', target: '_blank' %>
              <% else %>
                N/A
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/data_definitions/new.html.erb
<div class="modal-body">
  <h1>New Data Definition</h1>
  <%= render 'form', data_definition: @data_definition %>
  <%= link_to 'Back', data_definitions_path, :class => "btn btn-primary btn-sm" %>
</div>

app/views/data_definitions/show.html.erb
<div class="modal-body">
  <h1>Data Definition</h1>
  <div class="container-fluid">
    <div class="container">
      <div class="row row-cols-2">
        <div class="col">
          <h5><strong>db_section:</strong></h5>
        </div>
        <div class="col">
          <h5><%= @data_definition.db_section %></h5>
        </div>
        <div class="col">
          <h5><strong>table_name:</strong></h5>
        </div>
        <div class="col">
          <h5><%= @data_definition.table_name %></h5>
        </div>
        <div class="col">
          <h5><strong>column_name:</strong></h5>
        </div>
        <div class="col">
          <h5><%= @data_definition.column_name %></h5>
        </div>
        <div class="col">
          <h5><strong>data_type:</strong></h5>
        </div>
        <div class="col">
          <h5><%= @data_definition.data_type %></h5>
        </div>
        <div class="col">
          <h5><strong>source:</strong></h5>
        </div>
        <div class="col-6">
          <h5><%= @data_definition.source %></h5>
        </div>
        <div class="col">
          <h5><strong>ctti_note:</strong></h5>
        </div>
        <div class="col-6">
          <h5><%= @data_definition.ctti_note %></h5>
        </div>
        <div class="col">
          <h5><strong>nlm_link:</strong></h5>
        </div>
        <div class="col">
          <% if @data_definition.nlm_link.present? %>
            <% results_url = Util::FilePresentationManager.new.nlm_results_data_url %>
            <% protocol_url = Util::FilePresentationManager.new.nlm_protocol_data_url %>
            <% url = @data_definition.db_section.downcase == "results" ? results_url : protocol_url %>
            <%= link_to raw("<i class='fa fa-book'></i>"), "#{url}##{@data_definition.nlm_link}", class: 'navItem', target: '_blank' %>
          <% else %>
            N/A
          <% end %>
        </div>
      </div>  
    </div>  
    <div class="pb-5">
    </div>
    <div class="d-flex justify-content-between w-25">
      <div>
        <%= link_to 'Edit', edit_data_definition_path(@data_definition), :class => "btn btn-primary" %>   
      </div>
      <%= link_to 'Delete', data_definition_path(@data_definition), :class => "btn btn-danger", :method => :delete, data: { confirm: 'Are you sure?' } %>
      <div>
        <%= link_to 'Back', data_definitions_path, :class => "btn btn-primary" %>  
      </div>
    </div>
  </div>
</div>  