config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :notices
    get "/notices/:id/send_notice" => "notices#send_notice"
    get "dashboard", to: "database_usage#dashboard", as: :dashboard
    get "daily_usage/:date", to: "database_usage#daily_usage", as: :daily_usage
  end

  # Adding these routes connects those requests to the appropriate actions of the errors controller.
  # Using match ... :via => :all allows the error pages to be displayed for any type of request (GET, POST, PUT, etc.)
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords:     'users/passwords'}

  devise_scope :user do
    get 'users/password', :to => 'users/registrations#password'
  end

  root "pages#home"

  get 'file_records/active_url'
  get 'summary/aact'

  get "/airbrake"             => "pages#airbrake"

  get "/data_dictionary"      => "dictionary#show"
  get "/activities"           => "database_activity#show"
  get 'dictionary/show'
  # get "admin/notices/:id/send_notice" => "admin/notices#send_notice"
  get "/connect"              => "pages#connect"
  # TODO: remove legacy routes and its references
  # get "/download"             => "pages#download"
  # get "/covid_19"             => "pages#covid_19"
  # get "/snapshots"            => "pages#snapshots"
  # get "/pipe_files"           => "pages#pipe_files"
  get 'faq'                   => "pages#faq"
  get "/learn_more"           => "pages#learn_more"
  get "/covid_19_fields"      => "pages#covid_19_fields"
  get "/pipe_files_with_r"    => "pages#pipe_files_with_r"
  get "/pipe_files_with_sas"  => "pages#pipe_files_with_sas"
  get "/pgadmin"              => "pages#pgadmin"
  get "/points_to_consider"   => "pages#points_to_consider"
  get "/postgres"             => "pages#postgres"
  get "/r"                    => "pages#r"
  get "/sanity_check_report"  => "pages#sanity_check", as: :sanity_check
  get "/sas"                  => "pages#sas"
  get "/saved_query_doc"      => "pages#saved_query_doc"
  get "/schema"               => "pages#schema"
  get "/snapshot_archive"     => "pages#snapshot_archive"
  get "/technical_documentation"    => "pages#technical_documentation"
  get "/update_policy"        => "pages#update_policy"
  get "/deploy_code"          => "pages#deploy_code"
  get "/contactus"            => "pages#contactus"

  get '/history', to: 'background_jobs#history'
  get '/admin/history', to: 'background_jobs#admin_history'
  get '/queries', to: 'saved_queries#index'
  get '/my/queries', to: 'saved_queries#my_queries'
  get "/playground"           => "playground#index", as: :playground
  get "/playground/:id"       => "playground#show_results", as: :show_results
  get "job_status/:id"        => "playground#job_status", as: :job_status
  get "/install_postgres"     => "postgres_documentation#install_postgres"
  get "/credentials"          => "credentials#show"

  get "/admin_run_loads"      => "faq#admin_run_loads"
  get "/admin_remove_user"    => "faq#admin_remove_user"
  get "/admin_add_project"    => "faq#admin_add_project"
  get "/faq_proj_gather_info" => "faq#proj_gather_info"
  get "/faq_proj_change_app"  => "faq#proj_change_app"

  get "/support_grant_permission"  => "faq#support_grant_permission"
  get "/support_registration_failed"  => "faq#support_registration_failed"
  get "/support_user_cannot_access_db"  => "faq#support_user_cannot_access_db"

  get "/tech_access_servers"  => "faq#tech_access_servers"
  get "/tech_apply_ctgov_changes"  => "faq#tech_apply_ctgov_changes"
  get "/tech_deploy_code"     => "faq#tech_deploy_code"

  #beta
  get "/beta/migration" => "beta#migration"
  get "/beta/schema"     => "beta#schema"
  get "/beta/data_dictionary" => "beta#data_dictionary"

  #archive
  get "/archive"           => "archive#archive"
  get "/archive/data_dictionary" => "archive#data_dictionary"
  get "/archive/schema"    => "archive#schema"
  get "/archive/download"  => "archive#download"
  get "/archive/snapshots" => "archive#snapshots"
  get "/archive/pipe_files" => "archive#pipe_files"
  get "/archive/covid_19"   => "archive#covid_19"
  get "/archive/pipe_files_with_r"    => "archive#pipe_files_with_r"
  get "/archive/pipe_files_with_sas"  => "archive#pipe_files_with_sas"

  #digitalocean
  get "/static/:type/:time/:filename(:format)" => "file_records#active_url"

  resources :documentation, only: [:index, :show, :edit, :update] do
    collection do
      get :download_csv
    end
  end

  # TODO: review and optimize naming before releasing
  resources :downloads, only: [:index] do
    collection do
      get 'snapshots'
      get 'postgres_instructions'
      get 'flatfiles_instructions'
      get 'covid19_instructions'
    end
  end


  resources :file_records, only: [:index, :show]
  resources :definitions, only: [:index]
  resources :data_definitions
  resources :users
  resources :shared_data, param: :schema_name
  resources :release_notes
  resources :releases
  resources :datasets
  resources :attachments
  resources :use_cases
  resources :use_case_attachments
  resources :events
  resources :verifiers
  resources :saved_queries
  resources :study_statistics_comparisons
  resources :background_jobs, path: '/history', only: [:index, :show, :destroy]
  resources :study_searches

end

app/models/saved_query.rb
class SavedQuery < ActiveRecord::Base
  belongs_to :user
  validates :title, :description, :sql, presence: true
end

app/controllers/saved_queries_controller.rb
class SavedQueriesController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  before_action :set_saved_query, only: [:edit, :update, :destroy]

  def index
    base_query = SavedQuery.where(public: true)

    if user_signed_in?
      base_query = base_query.or(SavedQuery.where(public: false, user_id: current_user.id))
    end
    
    if params[:search].present? || params[:search].blank?
      search_term = "%#{params[:search]}%"
      @saved_queries = base_query
        .where("LOWER(title) LIKE ? OR LOWER(description) LIKE ?", search_term.downcase, search_term.downcase)
        .order(created_at: :desc)
        .page(params[:page])
        .per(20)
    else
      @saved_queries = base_query
        .order(created_at: :desc)
        .page(params[:page])
        .per(20)
    end
  end
  
  def my_queries
    if params[:search].present? || params[:search].blank?
      search_term = "%#{params[:search]}%"
      @my_queries = SavedQuery.where(user_id: current_user.id)
                              .where("LOWER(title) LIKE ? OR LOWER(description) LIKE ?", search_term.downcase, search_term.downcase)
                              .order(created_at: :desc)
                              .page(params[:page])
                              .per(20)
    else
      @my_queries = SavedQuery.where(user_id: current_user.id)
                              .order(created_at: :desc)
                              .page(params[:page])
                              .per(20)
    end
  end
  
  def new
    @saved_query = SavedQuery.new
  end

  def show
    @saved_query = SavedQuery.find_by_id(params[:id])
    if @saved_query.nil? || (@saved_query.user_id != current_user.id && !@saved_query.public)
      render :file => "app/views/errors/not_found.html", status: :not_found
    end
  end

  def edit
    unless current_user.admin? || current_user == @saved_query.user
      redirect_to :root, alert: "You are not authorized to edit this query."
    end
  end

  def create
    @saved_query = SavedQuery.new(saved_query_params)
    @saved_query.user_id = current_user.id
    if @saved_query.save
      redirect_to saved_query_path(@saved_query), notice: "The query was created successfully."
    else
      flash.now.alert = @saved_query.errors.full_messages.to_sentence
      render :new
    end
  end

  def update
    unless current_user.admin? || current_user == @saved_query.user
      redirect_to :root, alert: "You are not authorized to update this query."
      return
    end

    if @saved_query.update(saved_query_params)
      flash.notice = "The query was updated successfully."
      redirect_to @saved_query
    else
      flash.now.alert = @saved_query.errors.full_messages.to_sentence
      render :edit  
    end  
  end

  def destroy
    unless current_user.admin? || current_user == @saved_query.user
      redirect_to :root, alert: "You are not authorized to delete this query."
      return
    end

    @saved_query.destroy
    redirect_to saved_queries_path, notice: "The query was deleted successfully."
  end

  private
    def set_saved_query
      @saved_query = SavedQuery.find_by_id(params[:id])
      if @saved_query.nil? || (@saved_query.user_id != current_user.id && !current_user.admin?)
        render :file => "app/views/errors/not_found.html", status: :not_found
      end
    end

    # Only allow a list of trusted parameters through.
    def saved_query_params
      params.require(:saved_query).permit(:title, :description, :sql, :public)
    end
end

app/views/saved_queries/_form.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/codemirror.min.css" integrity="sha512-uf06llspW44/LZpHzHT6qBOIVODjWtv4MxCricRxkzvopAlSWnTf6hpZTFxuuZcuNE9CBQhqE0Seu1CoRk84nQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/codemirror.min.js" integrity="sha512-rdFIN28+neM8H8zNsjRClhJb1fIYby2YCNmoqwnqBDEvZgpcp7MJiX8Wd+Oi6KcJOMOuvGztjrsI59rly9BsVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/edit/matchbrackets.min.js" integrity="sha512-GSYCbN/le5gNmfAWVEjg1tKnOH7ilK6xCLgA7c48IReoIR2g2vldxTM6kZlN6o3VtWIe6fHu/qhwxIt11J8EBA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/mode/sql/sql.min.js" integrity="sha512-fb0A/RjJvLbWBSNDDNRUER4LHrkVQjlEs3a2myQH047y9+I6wZAZOboHn+EA7ZcEcVwSiH3okO/+XzMlGPqcow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/hint/show-hint.min.css" integrity="sha512-W/cvA9Wiaq79wGy/VOkgMpOILyqxqIMU+rkneDUW2uqiUT53I6DKmrF4lmCbRG+/YrW0J69ecvanKCCyb+sIWA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/hint/show-hint.min.js" integrity="sha512-4+hfJ/4qrBFEm8Wdz+mXpoTr/weIrB6XjJZAcc4pE2Yg5B06aKS/YLMN5iIAMXFTe0f1eneuLE5sRmnSHQqFNg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/hint/sql-hint.min.js" integrity="sha512-Pue0eeX9BJ4IA+BRNDOFwhQmxPjXIHiHOsvHNc9dQ+3J43swbPQDT9gwC8lzE1TTjR8iIxOd+lNiv4oTBRWqYw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/theme/monokai.min.css" integrity="sha512-R6PH4vSzF2Yxjdvb2p2FA06yWul+U0PDDav4b/od/oXf9Iw37zl10plvwOXelrjV2Ai7Eo3vyHeyFUjhXdBCVQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<%= form_for(saved_query) do |f| %>
  <% if saved_query.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(saved_query.errors.count, "error") %> prohibited this query from being saved:</h2>
      <ul>
        <% saved_query.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="modal-body">
    <div class="container-fluid">
      <%= f.label :title %>
      <%= f.text_field :title, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :description %>
      <%= f.text_area :description, rows: 5, class: "form-control" %>
    </div>
    <div class="container-fluid">
      <%= f.label :sql %>
      <%= f.text_area :sql, id: "query" %>
    </div>
    <div class="pb-3"></div>
    <div class="container-fluid">
      <div class="form-check" >
        <%= f.check_box :public, class: "form-check-input" %>
        <%= f.label :public, "Public", class: "form-check-label" %>
        <small>A public query will be visible to anyone</small> 
      </div>
    </div>
    <div class="pb-5"></div>
    <div class="container-fluid">
      <%= f.button "Save", type: "submit", :class => "btn btn-primary btn-sm" %>
    </div>
  </div>
<% end %>

<script>
  CodeMirror.fromTextArea(document.getElementById('query'), {
    mode: 'sql',
    indentWithTabs: true,
    smartIndent: true,
    lineNumbers: true,
    matchBrackets : true,
    autofocus: true,
    theme: 'monokai',
    extraKeys: {"Ctrl-Space": "autocomplete"}
  });      
</script>

app/views/saved_queries/edit.html.erb
<div class="modal-body">
  <%= render 'layouts/query_menu' %>
  <span class="h4">Edit Query:</span>
  <%= render 'form', saved_query: @saved_query %>
  <div class="modal-body">
    <div class="container-fluid">
      <%= link_to 'Back', saved_query_path(@saved_query), :class => "btn btn-primary btn-sm" %>
    </div>
  </div>  
</div>  

app/views/saved_queries/index.html.erb
  <%= render 'layouts/query_menu' %>
  <div class="search-form" style="display: flex; justify-content: space-between; align-items: center;">
    <%= form_tag(queries_path, method: :get, class: 'form-inline') do %>
      <div class="form-group" style="display: flex; align-items: center;">
        <%= text_field_tag :search, params[:search], class: 'form-control form-control-sm', style: 'width: 250px; margin-right: 10px;' %>
        <%= submit_tag "Search", class: 'btn btn-primary btn-sm', style: 'width: 100px;' %>
      </div>
    <% end %>
  </div>

  <table id="data-table" class="table table-sm table-striped">
    <tbody>
      <% @saved_queries.each do |query| %>
        <% if query.public %>
          <tr class="selectable-row" data-url="<%= saved_query_path(query) %>">
            <td>
              <%= link_to query.title, saved_query_path(query) %>
              <br>
              <%= query.description %>
            </td>
            <td class="text-right">
              <%= query.created_at.strftime('%B %d, %Y') %>
            </td>
          </tr>
        <% end %>
      <% end %>
    </tbody>
  </table>

  <div class="pagination">
    <%= paginate @saved_queries %>
</div>

app/views/saved_queries/my_queries.html.erb
  <%= render 'layouts/query_menu' %>

  <div class="search-form" style="display: flex; justify-content: space-between; align-items: center;">
    <%= form_tag(my_queries_path, method: :get, class: 'form-inline') do %>
      <div class="form-group" style="display: flex; align-items: center;">
        <%= text_field_tag :search, params[:search], class: 'form-control form-control-sm', style: 'width: 250px; margin-right: 10px;' %>
        <%= submit_tag "Search", class: 'btn btn-primary btn-sm', style: 'width: 100px;' %>
      </div>
    <% end %>
    <%= link_to 'New Query', new_saved_query_path, class: 'btn btn-primary btn-sm', style: 'margin-left: 10px;' %>
  </div>

  <table id="data-table" class="table table-sm table-striped">
    <tbody>
      <% @my_queries.each do |query| %>
        <tr class="selectable-row" data-url="<%= saved_query_path(query) %>">
          <td>
            <%= link_to query.title, saved_query_path(query), style: 'text-decoration: none;' %>
            <br>
            <%= query.description %>
          </td>
          <td class="text-right">
            <%= query.created_at.strftime('%B %d, %Y') %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
    
  <div class="pagination">
    <%= paginate @my_queries %>
</div>

app/views/saved_queries/new.html.erb
<div class="modal-body">
  <h1>New Query</h1>
  <%= render 'form', saved_query: @saved_query %>
  <div class="modal-body">
    <div class="container-fluid">
      <%= link_to 'Back', saved_queries_path, :class => "btn btn-primary btn-sm" %>
    </div>  
  </div>
</div>

app/views/saved_queries/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/codemirror.min.css" integrity="sha512-uf06llspW44/LZpHzHT6qBOIVODjWtv4MxCricRxkzvopAlSWnTf6hpZTFxuuZcuNE9CBQhqE0Seu1CoRk84nQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/codemirror.min.js" integrity="sha512-rdFIN28+neM8H8zNsjRClhJb1fIYby2YCNmoqwnqBDEvZgpcp7MJiX8Wd+Oi6KcJOMOuvGztjrsI59rly9BsVQ==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/edit/matchbrackets.min.js" integrity="sha512-GSYCbN/le5gNmfAWVEjg1tKnOH7ilK6xCLgA7c48IReoIR2g2vldxTM6kZlN6o3VtWIe6fHu/qhwxIt11J8EBA==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/mode/sql/sql.min.js" integrity="sha512-fb0A/RjJvLbWBSNDDNRUER4LHrkVQjlEs3a2myQH047y9+I6wZAZOboHn+EA7ZcEcVwSiH3okO/+XzMlGPqcow==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/hint/show-hint.min.css" integrity="sha512-W/cvA9Wiaq79wGy/VOkgMpOILyqxqIMU+rkneDUW2uqiUT53I6DKmrF4lmCbRG+/YrW0J69ecvanKCCyb+sIWA==" crossorigin="anonymous" referrerpolicy="no-referrer" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/hint/show-hint.min.js" integrity="sha512-4+hfJ/4qrBFEm8Wdz+mXpoTr/weIrB6XjJZAcc4pE2Yg5B06aKS/YLMN5iIAMXFTe0f1eneuLE5sRmnSHQqFNg==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/addon/hint/sql-hint.min.js" integrity="sha512-Pue0eeX9BJ4IA+BRNDOFwhQmxPjXIHiHOsvHNc9dQ+3J43swbPQDT9gwC8lzE1TTjR8iIxOd+lNiv4oTBRWqYw==" crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.65.11/theme/monokai.min.css" integrity="sha512-R6PH4vSzF2Yxjdvb2p2FA06yWul+U0PDDav4b/od/oXf9Iw37zl10plvwOXelrjV2Ai7Eo3vyHeyFUjhXdBCVQ==" crossorigin="anonymous" referrerpolicy="no-referrer" />

<div class="modal-body">
  <%= render 'layouts/query_menu' %>
  <div class="container-fluid">
    <h3><strong><%= @saved_query.title %></strong></h3>
  </div>
  <div class="container-fluid">
    <h5><%= @saved_query.description %></h5>
  </div>
  <div class="pb-3"></div>
  <%= form_tag("/playground", :method => "get") do %>
    <%= label_tag(:query, 'SQL Query:') %>
    <% if @error.present? %>
      <div id="error_explanation">
        <ul>
        <% @error.each do |message| %>
          <li class="text-danger"><%= message %></li>
        <% end %>
        </ul>
      </div>
    <% end %>
    <%= text_area_tag(:query, @saved_query.sql) %>
    <div class="pb-3"></div>
    <div class="d-flex">
      <div class="me-auto">
        <button type="submit" class="btn btn-primary btn-sm">Execute SQL Query</button>
      </div>
      <% if @saved_query.user_id == current_user.id || current_user.admin? %>
      <div class="d-flex gap-3">
        <div>
          <%= link_to 'Edit', edit_saved_query_path(@saved_query), :class => "btn btn-primary btn-sm" %>
        </div>
        <div>
          <%= link_to 'Delete', saved_query_path(@saved_query), :class => "btn btn-danger btn-sm", :method => :delete, data: { confirm: 'Are you sure?' } %>
        </div>
      </div>
      <% end %>
    </div>
  <% end %>
  <div class="pb-5"></div>
  <div>
    <%= link_to 'Back', saved_queries_path, :class => "btn btn-primary btn-sm" %>
  </div>
</div>

<script>
  CodeMirror.fromTextArea(document.getElementById('query'), {
    mode: 'sql',
    indentWithTabs: true,
    smartIndent: true,
    lineNumbers: true,
    matchBrackets : true,
    autofocus: true,
    theme: 'monokai',
    extraKeys: {"Ctrl-Space": "autocomplete"}
  });      
</script>