config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    resources :notices
    get "/notices/:id/send_notice" => "notices#send_notice"
    get "dashboard", to: "database_usage#dashboard", as: :dashboard
    get "daily_usage/:date", to: "database_usage#daily_usage", as: :daily_usage
  end

  # Adding these routes connects those requests to the appropriate actions of the errors controller.
  # Using match ... :via => :all allows the error pages to be displayed for any type of request (GET, POST, PUT, etc.)
  match "/404", to: "errors#not_found", via: :all
  match "/500", to: "errors#internal_server_error", via: :all

  devise_for :users, controllers: { registrations: 'users/registrations',
                                    confirmations: 'users/confirmations',
                                    passwords:     'users/passwords'}

  devise_scope :user do
    get 'users/password', :to => 'users/registrations#password'
  end

  root "pages#home"

  get 'file_records/active_url'
  get 'summary/aact'

  get "/airbrake"             => "pages#airbrake"

  get "/data_dictionary"      => "dictionary#show"
  get "/activities"           => "database_activity#show"
  get 'dictionary/show'
  # get "admin/notices/:id/send_notice" => "admin/notices#send_notice"
  get "/connect"              => "pages#connect"
  # TODO: remove legacy routes and its references
  # get "/download"             => "pages#download"
  # get "/covid_19"             => "pages#covid_19"
  # get "/snapshots"            => "pages#snapshots"
  # get "/pipe_files"           => "pages#pipe_files"
  get 'faq'                   => "pages#faq"
  get "/learn_more"           => "pages#learn_more"
  get "/covid_19_fields"      => "pages#covid_19_fields"
  get "/pipe_files_with_r"    => "pages#pipe_files_with_r"
  get "/pipe_files_with_sas"  => "pages#pipe_files_with_sas"
  get "/pgadmin"              => "pages#pgadmin"
  get "/points_to_consider"   => "pages#points_to_consider"
  get "/postgres"             => "pages#postgres"
  get "/r"                    => "pages#r"
  get "/sanity_check_report"  => "pages#sanity_check", as: :sanity_check
  get "/sas"                  => "pages#sas"
  get "/saved_query_doc"      => "pages#saved_query_doc"
  get "/schema"               => "pages#schema"
  get "/snapshot_archive"     => "pages#snapshot_archive"
  get "/technical_documentation"    => "pages#technical_documentation"
  get "/update_policy"        => "pages#update_policy"
  get "/deploy_code"          => "pages#deploy_code"
  get "/contactus"            => "pages#contactus"

  get '/history', to: 'background_jobs#history'
  get '/admin/history', to: 'background_jobs#admin_history'
  get '/queries', to: 'saved_queries#index'
  get '/my/queries', to: 'saved_queries#my_queries'
  get "/playground"           => "playground#index", as: :playground
  get "/playground/:id"       => "playground#show_results", as: :show_results
  get "job_status/:id"        => "playground#job_status", as: :job_status
  get "/install_postgres"     => "postgres_documentation#install_postgres"
  get "/credentials"          => "credentials#show"

  get "/admin_run_loads"      => "faq#admin_run_loads"
  get "/admin_remove_user"    => "faq#admin_remove_user"
  get "/admin_add_project"    => "faq#admin_add_project"
  get "/faq_proj_gather_info" => "faq#proj_gather_info"
  get "/faq_proj_change_app"  => "faq#proj_change_app"

  get "/support_grant_permission"  => "faq#support_grant_permission"
  get "/support_registration_failed"  => "faq#support_registration_failed"
  get "/support_user_cannot_access_db"  => "faq#support_user_cannot_access_db"

  get "/tech_access_servers"  => "faq#tech_access_servers"
  get "/tech_apply_ctgov_changes"  => "faq#tech_apply_ctgov_changes"
  get "/tech_deploy_code"     => "faq#tech_deploy_code"

  #beta
  get "/beta/migration" => "beta#migration"
  get "/beta/schema"     => "beta#schema"
  get "/beta/data_dictionary" => "beta#data_dictionary"

  #archive
  get "/archive"           => "archive#archive"
  get "/archive/data_dictionary" => "archive#data_dictionary"
  get "/archive/schema"    => "archive#schema"
  get "/archive/download"  => "archive#download"
  get "/archive/snapshots" => "archive#snapshots"
  get "/archive/pipe_files" => "archive#pipe_files"
  get "/archive/covid_19"   => "archive#covid_19"
  get "/archive/pipe_files_with_r"    => "archive#pipe_files_with_r"
  get "/archive/pipe_files_with_sas"  => "archive#pipe_files_with_sas"

  #digitalocean
  get "/static/:type/:time/:filename(:format)" => "file_records#active_url"

  resources :documentation, only: [:index, :show, :edit, :update] do
    collection do
      get :download_csv
    end
  end

  # TODO: review and optimize naming before releasing
  resources :downloads, only: [:index] do
    collection do
      get 'snapshots'
      get 'postgres_instructions'
      get 'flatfiles_instructions'
      get 'covid19_instructions'
    end
  end


  resources :file_records, only: [:index, :show]
  resources :definitions, only: [:index]
  resources :data_definitions
  resources :users
  resources :shared_data, param: :schema_name
  resources :release_notes
  resources :releases
  resources :datasets
  resources :attachments
  resources :use_cases
  resources :use_case_attachments
  resources :events
  resources :verifiers
  resources :saved_queries
  resources :study_statistics_comparisons
  resources :background_jobs, path: '/history', only: [:index, :show, :destroy]
  resources :study_searches

end

app/models/notice.rb
class Notice < ActiveRecord::Base
  belongs_to :user

  validates :title, :user_id, presence: true
  validates :body, presence: true, length: { minimum: 10 }

  # we want to send notice but haven't done it yet
  scope :unsent, -> { where(emails_sent_at: nil, send_emails: true) }
  # we want to send notice and already did it
  scope :sent, -> { where(send_emails: true).where.not(emails_sent_at: nil)}

  scope :invisible, -> { where(visible: false) }
  scope :visible, -> { where(visible: true)}

  def send_notice
    users = User.all.order(email: :asc)
    remaining = users.count
    users.each do |user|
      puts "#{remaining} #{user.email}"
      NoticeMailer.notice_to_mail(user.email, self).deliver_now
    end
    self.emails_sent_at = Time.now
    self.save
  end

end

app/controllers/admin/notices_controller.rb
class Admin::NoticesController < ApplicationController
  rescue_from ActiveRecord::RecordNotFound, with: :catch_not_found

  before_action :set_notice, only: [:show, :edit, :update, :destroy, :send_notice]
  before_action :is_admin?
  def index
    @notices= Notice.order(created_at: :desc)
  end

  def new
    @notice= Notice.new
  end

  def create
    @notice = Notice.new(notice_params)
    @notice.user = current_user
    if @notice.save
      redirect_to admin_notice_path(@notice), notice: 'Notice was successfully created.'
    else
      render :new
    end
  end

  def send_notice
    @notice.send_notice
    if !@notice.emails_sent_at.nil?
      redirect_to admin_notice_path(@notice), notice: 'Notice was sent.'
    else
      redirect_to admin_notice_path(@notice), alert: 'Something went wrong. Please try again.'
    end

  end

  def edit
  end

  def show   
  end

  def update
    if @notice.update(notice_params)   
      redirect_to admin_notice_path(@notice), notice: 'Notice was successfully updated.'
    else
      # alert_errors @notice
      render :edit
    end
  end

  def destroy
    @notice.destroy
    redirect_to admin_notices_path, alert: 'Notice was destroyed.'
  end

  private
  def set_notice
    @notice = Notice.find(params[:id])
  end

  def notice_params
    params.require(:notice).permit(:body, :title, :user_id, :visible, :send_emails)
  end

  def catch_not_found(e)
    Rails.logger.debug("We had a not found exception.")
    flash.alert = e.to_s
    redirect_to admin_notices_path
  end

end

app/views/admin/notices/_form.html.erb
<%= form_for([:admin, @notice]) do |f| %>
  <% if @notice.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@notice.errors.count, "error") %> prohibited this notice from being saved:</h2>
      <ul>
      <% @notice.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container">

    <div class="field">
      <%= f.label :title %>
      <%= f.text_field :title, disabled: !@notice.emails_sent_at.nil? %>
    </div>

    <div class="field mb-4">
      <%= f.label :body%>
      <%= f.text_area :body, rows: 6, disabled: !@notice.emails_sent_at.nil? %>
    </div>
     
     <div class= "inline-checkbox">
      <%= f.check_box :visible, {}, "true", "false" %>
      <%= f.label :visible %>
    </div>

    <div class= "inline-checkbox">
      <%= f.check_box :send_emails, {disabled: !@notice.emails_sent_at.nil?}, "true", "false"%>
      <%= f.label :send_emails %>    
    </div>
    <div>
      <%= f.submit "Save" , class: "old-btn" %>
    </div>
    <%= link_to 'Back', :back%>
  </div>
<% end %>

app/views/admin/notices/edit.html.erb
<div class="container">
  <h1>Edit Notice</h1>
  <%= render 'form', notice: @notice %>
</div>

app/views/admin/notices/index.html.erb
<div class="container">
  <div class="pb-5" >
    <h1>Notices</h1>
  <% if @notices.empty? %>
  <p> There is no Notices yet. You can click the button below to create one.</p>
    <%= link_to 'New Notification', new_admin_notice_path, :class => "btn btn-primary btn-sm" %>
  </div>
  <% else %>
    <%= link_to 'New Notice', new_admin_notice_path, :class => "btn btn-primary btn-sm" %>
  <table class="table table-sm table-striped" style="max-width: 100rem;">
    <thead>
      <tr>
        <th>Title</th>
        <th>Created at</th>
        <th>Visible</th>
        <th>Sent</th>
        <th colspan="2"></th>
      </tr>
    </thead>
    <tbody>
      <% @notices.each do |notice| %>
        <tr style= "vertical-align: middle;">
          <td><%= link_to notice.title, admin_notice_path(notice) %> </td>
          <td><%= notice.created_at.strftime('%B %d, %Y') %></td>
          <td><% if notice.visible? %>
              <i class="fa fa-check"></i>
              <%end%>
          </td>
          <td><% if !notice.send_emails? %>
                Not for sending
              <%elsif notice.send_emails? && notice.emails_sent_at?%>
                <%= notice.emails_sent_at.strftime('%B %d, %Y') %>
              <%else notice.send_emails? && !notice.emails_sent_at?%> 
                Not sent yet
              <%end%>
          </td>
          <td><%= link_to 'Edit', edit_admin_notice_path(notice), class: "btn btn-primary btn-sm mb-2" %></td>
          <!-- data confirmation not working, need to investigate -->
          <td><%= button_to'Delete', admin_notice_path(notice), method: :delete, class: "btn btn-danger btn-sm mb-2" %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>
</div>

app/views/admin/notices/new.html.erb
<div class="container">
  <h1>New Notice</h1>
  <%= render 'form', notice: @notice %>
</div>

app/views/admin/notices/show.html.erb
<div class="container">
  
    <table class="notice-header">
      <tr>
        <th>From:</th>
        <td>aact@ctti-clinicaltrials.org</td>
      </tr>
      <tr>
        <th>Date:</th>
        <td><%=@notice.created_at.strftime('%B %d, %Y')%></td>
      </tr>

      <% if @notice.send_emails? && @notice.emails_sent_at?%>
      <tr>
          <th>Sent at:</th>
          <td><%=@notice.emails_sent_at.strftime('%B %d, %Y')%></td>
      </tr>
      <%end%>

      <tr>
        <th>Subject:</th>
        <td><%=@notice.title%></td>
       </tr>
    </table>

    <hr/>
    <p><%= @notice.body %></p>
    <hr/>
    
      
  <div>
    <%= link_to 'Edit', edit_admin_notice_path(@notice), class: "btn btn-primary btn-sm pr-4", style:"margin:1rem" %>
    
    <% if @notice.send_emails? && @notice.emails_sent_at.nil? %>  
      <%= link_to 'Send', "/admin/notices/#{@notice.id}/send_notice", :class =>"btn btn-primary btn-sm pr-4", style:"margin:1rem" %> 
    <%end%>  
  </div>

  
  <%= link_to 'Back', admin_notices_path %>

</div>